# Generator for Master_Inventory_Import.csv from Menu PS version.docx with quoted CSV strings

$items = @(
    # --- MEAT & POULTRY (CAT-MEAT) ---
    [PSCustomObject]@{ itemCode="RM0101"; itemName="Chicken Boneless (Thigh & Breast)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-CHK-BL"; lastPurchasePrice="280.00"; purchaseTaxProfile="5% GST"; reorderLevel="15.0"; minimumStockLevel="8.0"; maximumStockLevel="60.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="90.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0102"; itemName="Whole Chicken (Curry Cut)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-CHK-WHL"; lastPurchasePrice="220.00"; purchaseTaxProfile="5% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="40.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="85.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0103"; itemName="Chicken Mince (Keema)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-CHK-MNC"; lastPurchasePrice="310.00"; purchaseTaxProfile="5% GST"; reorderLevel="8.0"; minimumStockLevel="4.0"; maximumStockLevel="30.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0104"; itemName="Chicken Wings & Lollipops"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-CHK-WNG"; lastPurchasePrice="240.00"; purchaseTaxProfile="5% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="40.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="85.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0105"; itemName="Mutton Curry Cut (Bone-in)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-MUT-CUT"; lastPurchasePrice="750.00"; purchaseTaxProfile="5% GST"; reorderLevel="12.0"; minimumStockLevel="6.0"; maximumStockLevel="45.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="80.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0106"; itemName="Mutton Mince (Keema)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-MUT-MNC"; lastPurchasePrice="820.00"; purchaseTaxProfile="5% GST"; reorderLevel="8.0"; minimumStockLevel="4.0"; maximumStockLevel="30.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0107"; itemName="Mutton Paya (Trotters for Broth)"; itemType="Raw Material"; categoryCode="CAT-MEAT"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-MUT-PAYA"; lastPurchasePrice="450.00"; purchaseTaxProfile="5% GST"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="75.0"; departmentUsageScope="KITCHEN" },

    # --- SEAFOOD (CAT-SEAFOOD) ---
    [PSCustomObject]@{ itemCode="RM0201"; itemName="Bombil / Bombay Duck (Fresh)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-FISH-BMB"; lastPurchasePrice="320.00"; purchaseTaxProfile="5% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="30.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="75.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0202"; itemName="Surmai / Seer Fish (King Mackerel)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-FISH-SUR"; lastPurchasePrice="950.00"; purchaseTaxProfile="5% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="35.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="80.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0203"; itemName="Pomfret (Silver / Black)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-FISH-POM"; lastPurchasePrice="1100.00"; purchaseTaxProfile="5% GST"; reorderLevel="8.0"; minimumStockLevel="4.0"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="75.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0204"; itemName="Rawas / Indian Salmon"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-FISH-RAW"; lastPurchasePrice="1050.00"; purchaseTaxProfile="5% GST"; reorderLevel="8.0"; minimumStockLevel="4.0"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="82.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0205"; itemName="Dadha / Indian Threadfin"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-FISH-DAD"; lastPurchasePrice="880.00"; purchaseTaxProfile="5% GST"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="80.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0206"; itemName="Tiger Prawns (Cleaned & Deveined)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-SEAF-PRW"; lastPurchasePrice="850.00"; purchaseTaxProfile="5% GST"; reorderLevel="15.0"; minimumStockLevel="8.0"; maximumStockLevel="50.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="70.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0207"; itemName="Mud Crab (Live / Cleaned)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-SEAF-CRB"; lastPurchasePrice="1200.00"; purchaseTaxProfile="5% GST"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="60.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0208"; itemName="Rock Lobster (Fresh)"; itemType="Raw Material"; categoryCode="CAT-SEAFOOD"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-002"; supplierItemCode="SKU-SEAF-LOB"; lastPurchasePrice="2400.00"; purchaseTaxProfile="5% GST"; reorderLevel="3.0"; minimumStockLevel="1.0"; maximumStockLevel="10.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="55.0"; departmentUsageScope="KITCHEN" },

    # --- VEGETABLES & FRESH PRODUCE (CAT-PRODUCE) ---
    [PSCustomObject]@{ itemCode="RM0301"; itemName="Fresh Paneer (Malai)"; itemType="Raw Material"; categoryCode="CAT-DAIRY"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-DRY-PNR"; lastPurchasePrice="380.00"; purchaseTaxProfile="5% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="30.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0302"; itemName="Colocasia Leaves (Alu Leaves)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-ALU"; lastPurchasePrice="120.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="4.0"; minimumStockLevel="2.0"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="85.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0303"; itemName="Raw Banana (Kacha Kela)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-RBN"; lastPurchasePrice="45.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="75.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0304"; itemName="Raw Jackfruit (Phanas)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-JFK"; lastPurchasePrice="90.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="8.0"; minimumStockLevel="4.0"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="70.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0305"; itemName="Button Mushrooms"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="PACK"; conversionFactor="0.25"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-MSH"; lastPurchasePrice="60.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="90.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0306"; itemName="Small Brinjal (Vangi)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-BNJ"; lastPurchasePrice="50.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="90.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0307"; itemName="Baby Corn & Cauliflower"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-BCN"; lastPurchasePrice="110.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="80.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0308"; itemName="Sprouted Green Gram (Moong)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-MNG"; lastPurchasePrice="140.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="4.0"; minimumStockLevel="2.0"; maximumStockLevel="12.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0309"; itemName="Red & White Onions"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="50"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-ONN"; lastPurchasePrice="1500.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="30.0"; minimumStockLevel="15.0"; maximumStockLevel="150.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="88.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0310"; itemName="Tomatoes (Ripe & Charred)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="CRATE"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-TOM"; lastPurchasePrice="750.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="20.0"; minimumStockLevel="10.0"; maximumStockLevel="100.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="92.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0311"; itemName="Fresh Herbs (Coriander, Mint, Parsley)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-HRB"; lastPurchasePrice="160.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="80.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0312"; itemName="Green Chillies & Byadagi Chillies"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-CHL"; lastPurchasePrice="120.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0313"; itemName="Fresh Coconut (Gratable)"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="PCS"; purchaseUom="BAG"; conversionFactor="50"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-CCN"; lastPurchasePrice="1250.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="30.0"; minimumStockLevel="15.0"; maximumStockLevel="150.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="75.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0314"; itemName="Fresh Kokum & Kokum Extract"; itemType="Raw Material"; categoryCode="CAT-PRODUCE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-004"; supplierItemCode="SKU-VEG-KOK"; lastPurchasePrice="280.00"; purchaseTaxProfile="5% GST"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },

    # --- GRAINS, FLOURS & DAIRY (CAT-GRAIN & CAT-DAIRY) ---
    [PSCustomObject]@{ itemCode="RM0401"; itemName="Kolam Rice (Steamed)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-KLM"; lastPurchasePrice="1450.00"; purchaseTaxProfile="5% GST"; reorderLevel="50.0"; minimumStockLevel="25.0"; maximumStockLevel="200.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0402"; itemName="Indrayani Rice (Sticky)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-IND"; lastPurchasePrice="1650.00"; purchaseTaxProfile="5% GST"; reorderLevel="30.0"; minimumStockLevel="15.0"; maximumStockLevel="150.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0403"; itemName="Basmati Rice (Long Grain Biryani)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-BSM"; lastPurchasePrice="2850.00"; purchaseTaxProfile="5% GST"; reorderLevel="40.0"; minimumStockLevel="20.0"; maximumStockLevel="150.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0404"; itemName="Rice Flour (Tandalachi Pithi)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-RFL"; lastPurchasePrice="1150.00"; purchaseTaxProfile="5% GST"; reorderLevel="20.0"; minimumStockLevel="10.0"; maximumStockLevel="80.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0405"; itemName="Whole Wheat Atta & Maida"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="25"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-ATA"; lastPurchasePrice="980.00"; purchaseTaxProfile="5% GST"; reorderLevel="30.0"; minimumStockLevel="15.0"; maximumStockLevel="100.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0406"; itemName="Millet Flour Mix (Ragi, Jowar, Bajra)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="10"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-MLT"; lastPurchasePrice="650.00"; purchaseTaxProfile="5% GST"; reorderLevel="15.0"; minimumStockLevel="8.0"; maximumStockLevel="50.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0407"; itemName="Tur Dal & Yellow Lentils"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="30"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-GRN-TUR"; lastPurchasePrice="3900.00"; purchaseTaxProfile="5% GST"; reorderLevel="25.0"; minimumStockLevel="12.0"; maximumStockLevel="90.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0408"; itemName="Amul Butter (Unsalted / Salted)"; itemType="Raw Material"; categoryCode="CAT-DAIRY"; baseUom="KG"; purchaseUom="PACK"; conversionFactor="0.5"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-DRY-BUT"; lastPurchasePrice="260.00"; purchaseTaxProfile="12% GST"; reorderLevel="15.0"; minimumStockLevel="8.0"; maximumStockLevel="50.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0409"; itemName="Desi Cow Ghee (Pure)"; itemType="Raw Material"; categoryCode="CAT-OIL"; baseUom="KG"; purchaseUom="TIN"; conversionFactor="15"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-OIL-GHE"; lastPurchasePrice="9800.00"; purchaseTaxProfile="12% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="45.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0410"; itemName="Pressed Mustard Oil & Coconut Oil"; itemType="Raw Material"; categoryCode="CAT-OIL"; baseUom="LTR"; purchaseUom="TIN"; conversionFactor="15"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-OIL-MST"; lastPurchasePrice="2850.00"; purchaseTaxProfile="5% GST"; reorderLevel="15.0"; minimumStockLevel="8.0"; maximumStockLevel="60.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0411"; itemName="Coconut Milk & Cream"; itemType="Raw Material"; categoryCode="CAT-DAIRY"; baseUom="LTR"; purchaseUom="BOX"; conversionFactor="12"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-DRY-CCM"; lastPurchasePrice="1800.00"; purchaseTaxProfile="12% GST"; reorderLevel="24.0"; minimumStockLevel="12.0"; maximumStockLevel="96.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },

    # --- SPECIALTY MASALAS & CONDIMENTS (CAT-SPICE) ---
    [PSCustomObject]@{ itemCode="RM0501"; itemName="Kasundi Mustard Paste"; itemType="Raw Material"; categoryCode="CAT-SPICE"; baseUom="KG"; purchaseUom="JAR"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-SPC-KAS"; lastPurchasePrice="320.00"; purchaseTaxProfile="12% GST"; reorderLevel="3.0"; minimumStockLevel="1.0"; maximumStockLevel="12.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0502"; itemName="Goan Toddy Vinegar / Sugarcane Vinegar"; itemType="Raw Material"; categoryCode="CAT-SPICE"; baseUom="LTR"; purchaseUom="BOTTLE"; conversionFactor="0.75"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-SPC-VNG"; lastPurchasePrice="180.00"; purchaseTaxProfile="12% GST"; reorderLevel="6.0"; minimumStockLevel="3.0"; maximumStockLevel="24.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0503"; itemName="Triphal & Whole Black Peppercorns"; itemType="Raw Material"; categoryCode="CAT-SPICE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-SPC-PEP"; lastPurchasePrice="850.00"; purchaseTaxProfile="5% GST"; reorderLevel="3.0"; minimumStockLevel="1.5"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="RM0504"; itemName="Poppy Seeds (Khas Khas) & Mustard Seeds"; itemType="Raw Material"; categoryCode="CAT-SPICE"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-SPC-POP"; lastPurchasePrice="1400.00"; purchaseTaxProfile="5% GST"; reorderLevel="2.0"; minimumStockLevel="1.0"; maximumStockLevel="10.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },

    # --- SEMI FINISHED KITCHEN PREPS (CAT-PREP) ---
    [PSCustomObject]@{ itemCode="SF0001"; itemName="Signature Damao Masala Paste"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-DAM"; lastPurchasePrice="350.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="5.0"; minimumStockLevel="2.0"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0002"; itemName="Goan Recheado Red Spice Paste"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-RCH"; lastPurchasePrice="380.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="4.0"; minimumStockLevel="2.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0003"; itemName="Goan Green Cafreal Herb Marinade"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-CAF"; lastPurchasePrice="290.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="4.0"; minimumStockLevel="2.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0004"; itemName="Mangalorean Ghee Roast Masala"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-GHE"; lastPurchasePrice="450.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="3.0"; minimumStockLevel="1.5"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0005"; itemName="Goan Xacuti Roasted Coconut Masala"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-XAC"; lastPurchasePrice="310.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="4.0"; minimumStockLevel="2.0"; maximumStockLevel="20.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0006"; itemName="Malvani Roasted Coconut Rassa Base"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-PREP-MLV"; lastPurchasePrice="280.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="5.0"; minimumStockLevel="2.5"; maximumStockLevel="25.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="95.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0007"; itemName="Signature House Green Dip (Molho Verde)"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-DIP-GRN"; lastPurchasePrice="240.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="3.0"; minimumStockLevel="1.5"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="98.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0008"; itemName="Signature House Red Pepper Dip"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-DIP-RED"; lastPurchasePrice="260.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="3.0"; minimumStockLevel="1.5"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="98.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="SF0009"; itemName="Signature Mustard Coconut Dip"; itemType="Semi Finished"; categoryCode="CAT-PREP"; baseUom="KG"; purchaseUom="KG"; conversionFactor="1"; defaultLocationCode="LOC-CHILL"; preferredSupplierCode="SUP-001"; supplierItemCode="SKU-DIP-WHT"; lastPurchasePrice="280.00"; purchaseTaxProfile="0% Exempt"; reorderLevel="3.0"; minimumStockLevel="1.5"; maximumStockLevel="15.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="98.0"; departmentUsageScope="KITCHEN" },

    # --- BREADS & PACKAGING (CAT-GRAIN & CAT-PKG) ---
    [PSCustomObject]@{ itemCode="RM0601"; itemName="Goan Poi Breads (Traditional)"; itemType="Raw Material"; categoryCode="CAT-GRAIN"; baseUom="PCS"; purchaseUom="PACK"; conversionFactor="10"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-BRD-POI"; lastPurchasePrice="80.00"; purchaseTaxProfile="5% GST"; reorderLevel="30.0"; minimumStockLevel="15.0"; maximumStockLevel="100.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="PKG0001"; itemName="Millet Papads (Jowar, Bajra, Ragi)"; itemType="Packaging"; categoryCode="CAT-PKG"; baseUom="PACK"; purchaseUom="BOX"; conversionFactor="20"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-PKG-PPD"; lastPurchasePrice="600.00"; purchaseTaxProfile="12% GST"; reorderLevel="10.0"; minimumStockLevel="5.0"; maximumStockLevel="40.0"; isStockable="TRUE"; isRecipeIngredient="TRUE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" },
    [PSCustomObject]@{ itemCode="PKG0002"; itemName="Natural Charcoal Briquettes (Grill)"; itemType="Consumable"; categoryCode="CAT-CONS"; baseUom="KG"; purchaseUom="BAG"; conversionFactor="20"; defaultLocationCode="LOC-MWH"; preferredSupplierCode="SUP-003"; supplierItemCode="SKU-CNS-CHR"; lastPurchasePrice="1100.00"; purchaseTaxProfile="18% GST"; reorderLevel="40.0"; minimumStockLevel="20.0"; maximumStockLevel="150.0"; isStockable="TRUE"; isRecipeIngredient="FALSE"; autoDeductionEnabled="TRUE"; standardYieldPercent="100.0"; departmentUsageScope="KITCHEN" }
)

$csvPath = "D:\Projects\Anchor\Master_Inventory_Import.csv"

# Header line
$headers = "itemCode,itemName,itemType,categoryCode,baseUom,purchaseUom,conversionFactor,defaultLocationCode,preferredSupplierCode,supplierItemCode,lastPurchasePrice,purchaseTaxProfile,reorderLevel,minimumStockLevel,maximumStockLevel,isStockable,isRecipeIngredient,autoDeductionEnabled,standardYieldPercent,departmentUsageScope"
$csvLines = @($headers)

foreach ($i in $items) {
    $quotedName = '"' + $i.itemName.Replace('"', '""') + '"'
    $line = "$($i.itemCode),$quotedName,$($i.itemType),$($i.categoryCode),$($i.baseUom),$($i.purchaseUom),$($i.conversionFactor),$($i.defaultLocationCode),$($i.preferredSupplierCode),$($i.supplierItemCode),$($i.lastPurchasePrice),$($i.purchaseTaxProfile),$($i.reorderLevel),$($i.minimumStockLevel),$($i.maximumStockLevel),$($i.isStockable),$($i.isRecipeIngredient),$($i.autoDeductionEnabled),$($i.standardYieldPercent),$($i.departmentUsageScope)"
    $csvLines += $line
}

$csvLines | Out-File -FilePath $csvPath -Encoding utf8
Write-Host "Successfully generated Master_Inventory_Import.csv with quoted names for" $items.Count "master items!"
