# PowerShell script to sync Kitchen Domain Models & UI Components into bundle.js

$bundlePath = "d:\Projects\Anchor\bundle.js"
$menuDataPath = "d:\Projects\Anchor\restaurantos\frontend\capabilities\kitchen\data\actualMenuData.js"
$menuModelPath = "d:\Projects\Anchor\businessos\platform\kitchen\kitchenMenuModel.js"
$recipeModelPath = "d:\Projects\Anchor\businessos\platform\kitchen\recipeModel.js"
$prodModelPath = "d:\Projects\Anchor\businessos\platform\kitchen\productionModel.js"
$menuViewPath = "d:\Projects\Anchor\restaurantos\frontend\capabilities\kitchen\ui\KitchenMenuView.js"
$recipeViewPath = "d:\Projects\Anchor\restaurantos\frontend\capabilities\kitchen\ui\KitchenRecipeView.js"
$prodViewPath = "d:\Projects\Anchor\restaurantos\frontend\capabilities\kitchen\ui\KitchenProductionView.js"
$invViewPath = "d:\Projects\Anchor\restaurantos\frontend\capabilities\kitchen\ui\KitchenInventoryView.js"

# Read raw file contents UTF8
$menuData = Get-Content $menuDataPath -Raw -Encoding UTF8
$menuModel = Get-Content $menuModelPath -Raw -Encoding UTF8
$recipeModel = Get-Content $recipeModelPath -Raw -Encoding UTF8
$prodModel = Get-Content $prodModelPath -Raw -Encoding UTF8
$menuView = Get-Content $menuViewPath -Raw -Encoding UTF8
$recipeView = Get-Content $recipeViewPath -Raw -Encoding UTF8
$prodView = Get-Content $prodViewPath -Raw -Encoding UTF8
$invView = Get-Content $invViewPath -Raw -Encoding UTF8

# Function to clean ES Module syntax safely (only at start of lines)
function Clean-EsModule($code) {
  $c = $code -replace "(?m)^\s*import\s+.*?;?\r?\n", ""
  $c = $c -replace "(?m)^\s*export\s+const\s+", "const "
  $c = $c -replace "(?m)^\s*export\s+class\s+", "class "
  $c = $c -replace "(?m)^\s*export\s+let\s+", "let "
  $c = $c -replace "(?m)^\s*export\s+default\s+", ""
  return $c
}

$menuDataClean = Clean-EsModule $menuData
$menuModelClean = Clean-EsModule $menuModel
$recipeModelClean = Clean-EsModule $recipeModel
$prodModelClean = Clean-EsModule $prodModel

$menuViewClean = Clean-EsModule $menuView
$recipeViewClean = Clean-EsModule $recipeView
$prodViewClean = Clean-EsModule $prodView
$invViewClean = Clean-EsModule $invView

# Combine into single module block
$combinedKitchenModules = @"

// ====================================================================
// KITCHEN DOMAIN ENGINE & UI MODULES (AUTOGENERATED SYNC)
// ====================================================================

$menuDataClean

$menuModelClean

$recipeModelClean

$prodModelClean

$menuViewClean
const kitchenMenuView = new KitchenMenuView({});

$recipeViewClean

$prodViewClean

$invViewClean

"@

# Read clean bundle.js
$bundle = Get-Content $bundlePath -Raw -Encoding UTF8

# Remove any old kitchen block if already present
$markerStart = "// ===================================================================="
$appShellMarker = "class ApplicationShell"

if ($bundle.Contains($markerStart)) {
  $idxStart = $bundle.IndexOf($markerStart)
  $idxEnd = $bundle.IndexOf($appShellMarker)
  if ($idxStart -ge 0 -and $idxEnd -gt $idxStart) {
    $bundle = $bundle.Remove($idxStart, $idxEnd - $idxStart)
  }
}

# Find ApplicationShell position in clean bundle
$appShellPos = $bundle.IndexOf("class ApplicationShell")
if ($appShellPos -lt 0) {
  Write-Host "❌ Could not find class ApplicationShell in bundle.js"
  exit 1
}

# Insert kitchen modules block right before ApplicationShell
$bundle = $bundle.Substring(0, $appShellPos) + $combinedKitchenModules + "`n`n  " + $bundle.Substring($appShellPos)

# Update sidebar HTML for kitchen workspace with unicode escapes for emojis
$sidebarKitchenCode = @'
} else if (this.activeRoute === 'kitchen') {
        const v = this.kitchenActiveTab || 'catalog';
        mainNavHTML = `
          <div style="font-size:0.7rem; color:var(--text-muted); font-weight:700; text-transform:uppercase; margin-bottom:4px; padding-left:4px;">\u{1F468}\u{200D}\u{1F373} KITCHEN WORKSPACE</div>
          <button class="btn-secondary nav-kitchen-subtab ${v === 'catalog' ? 'active' : ''}" data-ktab="catalog" style="text-align:left; font-size:0.85rem; margin-bottom:2px;">\u{1F4CB} 1. Menu Catalog</button>
          <button class="btn-secondary nav-kitchen-subtab ${v === 'recipes' ? 'active' : ''}" data-ktab="recipes" style="text-align:left; font-size:0.85rem; margin-bottom:2px;">\u{1F373} 2. Recipe BOMs</button>
          <button class="btn-secondary nav-kitchen-subtab ${v === 'production' ? 'active' : ''}" data-ktab="production" style="text-align:left; font-size:0.85rem; margin-bottom:2px;">\u{1F958} 3. Production Engine</button>
          <button class="btn-secondary nav-kitchen-subtab ${v === 'stock' ? 'active' : ''}" data-ktab="stock" style="text-align:left; font-size:0.85rem; margin-bottom:2px;">\u{1F4E6} 4. Kitchen Inventory</button>
          <button class="btn-secondary nav-kitchen-subtab ${v === 'reports' ? 'active' : ''}" data-ktab="reports" style="text-align:left; font-size:0.85rem; margin-bottom:2px;">\u{1F4D8} 5. Kitchen Reports</button>
          
          <div style="font-size:0.65rem; color:var(--text-muted); font-weight:700; text-transform:uppercase; margin:12px 0 4px 4px;">DISPLAY MODES</div>
          <button class="btn-secondary nav-kitchen-kds" style="text-align:left; font-size:0.85rem; color:var(--status-danger);">\u{1F525} Live KDS Display</button>
        `;
'@

# Replace kitchen sidebar block
$idxKitchSide = $bundle.IndexOf("} else if (this.activeRoute === 'kitchen') {")
if ($idxKitchSide -ge 0) {
  $idxNextSide = $bundle.IndexOf("} else if (this.activeRoute === 'bar') {", $idxKitchSide)
  if ($idxNextSide -gt $idxKitchSide) {
    $bundle = $bundle.Remove($idxKitchSide, $idxNextSide - $idxKitchSide)
    $bundle = $bundle.Insert($idxKitchSide, $sidebarKitchenCode + "`n      ")
  }
}

# Replace renderKitchenWorkspace implementation
$oldKitchenWorkspacePattern = "renderKitchenWorkspace(mount, session) {"
$posKitch = $bundle.IndexOf($oldKitchenWorkspacePattern)
if ($posKitch -ge 0) {
  $nextMethodPos = $bundle.IndexOf("renderBarWorkspace(mount, session) {", $posKitch)
  if ($nextMethodPos -gt $posKitch) {
    $bundle = $bundle.Remove($posKitch, $nextMethodPos - $posKitch)
  }
}

$newKitchenWorkspaceRouter = @'
renderKitchenWorkspace(mount, session) {
    if (!this.kitchenActiveTab) this.kitchenActiveTab = 'catalog';

    const renderView = () => {
      mount.innerHTML = `
        <div class="animate-fade-in" style="display:flex; flex-direction:column; gap:20px; padding-bottom:40px;">
          <!-- Kitchen Top Cockpit Header -->
          <div class="card" style="background:var(--bg-surface-1); padding:20px; border:1px solid var(--border-subtle);">
            <div style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:16px;">
              <div>
                <div style="font-size:0.75rem; color:var(--text-muted); font-weight:700; text-transform:uppercase;">\u{1F468}\u{200D}\u{1F373} RESTAURANTOS CULINARY SUITE</div>
                <h2 style="font-size:1.75rem; margin-top:2px; margin-bottom:0;">\u{1F468}\u{200D}\u{1F373} Chef & Kitchen Operations Tower</h2>
                <div style="font-size:0.875rem; color:var(--text-muted); margin-top:4px;">
                  End-to-end culinary operations: Menu catalog, Recipe costing, Preparation BOM manufacturing, Operational stock view & Analytics.
                </div>
              </div>
              <div style="display:flex; align-items:center; gap:12px;">
                <button class="btn-primary btn-goto-kds" style="padding:10px 18px; font-weight:700; background:var(--status-danger);">
                  \u{1F525} Open Live KDS Display
                </button>
              </div>
            </div>

            <!-- Tab Navigation Bar (5 Tabs) -->
            <div style="display:flex; gap:8px; margin-top:20px; border-top:1px solid var(--border-subtle); padding-top:16px; flex-wrap:wrap;">
              <button class="btn-kitchen-tab ${this.kitchenActiveTab === 'catalog' ? 'active' : ''}" data-tab="catalog" style="padding:10px 20px; font-weight:700; font-size:0.9rem; border-radius:8px; cursor:pointer; background:${this.kitchenActiveTab === 'catalog' ? 'var(--accent-primary)' : 'var(--bg-surface-2)'}; color:${this.kitchenActiveTab === 'catalog' ? '#fff' : 'var(--text-primary)'}; border:1px solid var(--border-subtle);">
                \u{1F4CB} 1. Menu Catalog & KOTs
              </button>
              <button class="btn-kitchen-tab ${this.kitchenActiveTab === 'recipes' ? 'active' : ''}" data-tab="recipes" style="padding:10px 20px; font-weight:700; font-size:0.9rem; border-radius:8px; cursor:pointer; background:${this.kitchenActiveTab === 'recipes' ? 'var(--accent-primary)' : 'var(--bg-surface-2)'}; color:${this.kitchenActiveTab === 'recipes' ? '#fff' : 'var(--text-primary)'}; border:1px solid var(--border-subtle);">
                \u{1F373} 2. Recipe BOMs & Costing
              </button>
              <button class="btn-kitchen-tab ${this.kitchenActiveTab === 'production' ? 'active' : ''}" data-tab="production" style="padding:10px 20px; font-weight:700; font-size:0.9rem; border-radius:8px; cursor:pointer; background:${this.kitchenActiveTab === 'production' ? 'var(--accent-primary)' : 'var(--bg-surface-2)'}; color:${this.kitchenActiveTab === 'production' ? '#fff' : 'var(--text-primary)'}; border:1px solid var(--border-subtle);">
                \u{1F958} 3. Production Engine
              </button>
              <button class="btn-kitchen-tab ${this.kitchenActiveTab === 'stock' ? 'active' : ''}" data-tab="stock" style="padding:10px 20px; font-weight:700; font-size:0.9rem; border-radius:8px; cursor:pointer; background:${this.kitchenActiveTab === 'stock' ? 'var(--accent-primary)' : 'var(--bg-surface-2)'}; color:${this.kitchenActiveTab === 'stock' ? '#fff' : 'var(--text-primary)'}; border:1px solid var(--border-subtle);">
                \u{1F4E6} 4. Kitchen Inventory
              </button>
              <button class="btn-kitchen-tab ${this.kitchenActiveTab === 'reports' ? 'active' : ''}" data-tab="reports" style="padding:10px 20px; font-weight:700; font-size:0.9rem; border-radius:8px; cursor:pointer; background:${this.kitchenActiveTab === 'reports' ? 'var(--accent-primary)' : 'var(--bg-surface-2)'}; color:${this.kitchenActiveTab === 'reports' ? '#fff' : 'var(--text-primary)'}; border:1px solid var(--border-subtle);">
                \u{1F4D8} 5. Kitchen Reports
              </button>
            </div>
          </div>

          <!-- Active Subtab Content Body -->
          <main id="kitchen-subtab-body"></main>
        </div>
      `;

      const body = mount.querySelector('#kitchen-subtab-body');
      if (this.kitchenActiveTab === 'catalog') {
        body.appendChild(kitchenMenuView.render());
      } else if (this.kitchenActiveTab === 'recipes') {
        kitchenRecipeView.render(body, session);
      } else if (this.kitchenActiveTab === 'production') {
        kitchenProductionView.render(body, session);
      } else if (this.kitchenActiveTab === 'stock') {
        kitchenInventoryView.render(body, session);
      } else if (this.kitchenActiveTab === 'reports') {
        body.innerHTML = `
          <div class="card animate-fade-in" style="background:var(--bg-surface-1); padding:40px; text-align:center;">
            <div style="font-size:3rem; margin-bottom:12px;">\u{1F4D8}</div>
            <h2 style="font-size:1.6rem; margin-bottom:8px;">Tab 5 — Kitchen Reports & Analytics</h2>
            <p style="color:var(--text-muted); font-size:0.9rem; max-width:520px; margin:0 auto 20px;">
              Food cost calculations, preparation yield tracking, waste logs, ingredient consumption reports, and production performance analytics.
            </p>
            <span class="badge badge-info" style="font-size:0.85rem; padding:6px 14px;">Upcoming Tab</span>
          </div>
        `;
      }

      mount.querySelectorAll('.btn-kitchen-tab').forEach(btn => {
        btn.addEventListener('click', () => {
          this.kitchenActiveTab = btn.dataset.tab;
          this.render();
        });
      });

      const gotoKdsBtn = mount.querySelector('.btn-goto-kds');
      if (gotoKdsBtn) {
        gotoKdsBtn.addEventListener('click', () => {
          this.renderKDSWorkspace(mount, session);
        });
      }
    };

    renderView();
  }

  renderKDSWorkspace(mount, session) {
    const tickets = [
      { id: 'KOT-101', table: 'T-01', time: '5 mins ago', status: 'NEW', items: [{ name: 'Paneer Butter Masala', qty: 2, note: 'Less spicy' }, { name: 'Butter Naan', qty: 4, note: 'Extra butter' }] },
      { id: 'KOT-102', table: 'T-04', time: '12 mins ago', status: 'PREPARING', items: [{ name: 'Chicken Biryani (Handi)', qty: 1, note: 'Double Raita' }, { name: 'Garlic Naan', qty: 2, note: '' }] },
      { id: 'KOT-103', table: 'T-06', time: '20 mins ago', status: 'READY', items: [{ name: 'Dal Makhani', qty: 1, note: '' }, { name: 'Jeera Rice', qty: 2, note: '' }] }
    ];

    mount.innerHTML = `
      <div class="animate-fade-in" style="display:flex; flex-direction:column; gap:20px;">
        <div style="display:flex; justify-content:space-between; align-items:center;">
          <div>
            <h2 style="font-size:1.75rem; margin:0;">\u{1F468}\u{200D}\u{1F373} Kitchen Display System (KDS)</h2>
            <p style="color:var(--text-muted); font-size:0.875rem; margin-top:2px;">
              Live Food Ticket Queue & Preparation Control Tower
            </p>
          </div>
          <div style="display:flex; align-items:center; gap:12px;">
            <button class="btn-secondary nav-route-btn" data-r="kitchen">\u{1F468}\u{200D}\u{1F373} Exit to Chef Workspace</button>
            <span class="badge badge-info" style="font-size:0.85rem; padding:6px 12px;">\u{1F525} Live Orders: ${tickets.length}</span>
          </div>
        </div>

        <div class="grid grid-cols-3 gap-md">
          ${tickets.map(t => {
            const borderCol = t.status === 'NEW' ? 'var(--status-danger)' : (t.status === 'PREPARING' ? 'var(--status-warning)' : 'var(--status-success)');
            const badgeCls = t.status === 'NEW' ? 'badge-warning' : (t.status === 'PREPARING' ? 'badge-info' : 'badge-success');
            return `
              <div class="card" style="background:var(--bg-surface-1); border-top:4px solid ${borderCol}; display:flex; flex-direction:column; justify-content:space-between;">
                <div>
                  <div style="display:flex; justify-content:space-between; align-items:center;">
                    <strong style="font-size:1.1rem;">${t.id}</strong>
                    <span class="badge ${badgeCls}">${t.status}</span>
                  </div>
                  <div style="font-size:0.8rem; color:var(--text-muted); margin-top:2px;">Table: <strong>${t.table}</strong> • ${t.time}</div>

                  <div style="margin-top:12px; background:var(--bg-surface-2); padding:10px; border-radius:6px;">
                    ${t.items.map(i => `
                      <div style="display:flex; justify-content:space-between; font-size:0.9rem; margin-bottom:4px;">
                        <span><strong>${i.qty}x</strong> ${i.name}</span>
                      </div>
                      ${i.note ? `<div style="font-size:0.75rem; color:var(--status-warning); font-style:italic; margin-bottom:4px;">Note: ${i.note}</div>` : ''}
                    `).join('')}
                  </div>
                </div>

                <div style="margin-top:14px;">
                  ${t.status === 'NEW' ? `
                    <button class="btn-primary btn-kot-state" data-id="${t.id}" data-state="PREPARING" style="width:100%;">\u{1F525} Start Preparation</button>
                  ` : (t.status === 'PREPARING' ? `
                    <button class="btn-primary btn-kot-state" data-id="${t.id}" data-state="READY" style="width:100%; background:var(--status-success); border-color:var(--status-success);">✅ Mark Ticket Ready</button>
                  ` : `
                    <button class="btn-secondary" disabled style="width:100%; opacity:0.6;">✔ Ticket Ready & Dispatched</button>
                  `)}
                </div>
              </div>
            `;
          }).join('')}
        </div>
      </div>
    `;

    mount.querySelectorAll('.nav-route-btn').forEach(b => {
      b.addEventListener('click', () => {
        const r = b.dataset.r;
        if (r) window.location.hash = '#/' + r;
      });
    });

    mount.querySelectorAll('.btn-kot-state').forEach(b => {
      b.addEventListener('click', () => {
        alert(`✔ KOT ${b.dataset.id} status updated to ${b.dataset.state}!`);
      });
    });
  }

  
'@

$barPos = $bundle.IndexOf("renderBarWorkspace(mount, session) {")
if ($barPos -gt 0) {
  $bundle = $bundle.Substring(0, $barPos) + $newKitchenWorkspaceRouter + "`n`n  " + $bundle.Substring($barPos)
}

# Bind nav-kitchen-subtab and nav-kitchen-kds event listeners directly inside bindHeader
$oldBindHeaderEnd = "      this.appEl.querySelectorAll('.nav-route-btn').forEach(btn => {"
$newBindHeaderListeners = @'
      this.appEl.querySelectorAll('.nav-kitchen-subtab').forEach(btn => {
        btn.addEventListener('click', () => {
          this.kitchenActiveTab = btn.dataset.ktab;
          this.render();
        });
      });

      this.appEl.querySelectorAll('.nav-kitchen-kds').forEach(btn => {
        btn.addEventListener('click', () => {
          const mount = this.appEl.querySelector('#main-mount');
          if (mount) this.renderKDSWorkspace(mount, authEngine.getCurrentSession());
        });
      });

      this.appEl.querySelectorAll('.nav-route-btn').forEach(btn => {
'@

if ($bundle.Contains($oldBindHeaderEnd)) {
  $bundle = $bundle.Replace($oldBindHeaderEnd, $newBindHeaderListeners)
}

# Write out to bundle.js with explicit UTF8 Encoding
[System.IO.File]::WriteAllText($bundlePath, $bundle, [System.Text.Encoding]::UTF8)

Write-Host "✅ Successfully synchronized Kitchen Domain Engine, sidebar listeners & screen switching into bundle.js!"
